"use strict";
window.ROUTINE = {
  exercises: {
    floorpress: {name:"Press de pecho en el suelo", muscle:"Pecho · tríceps", dose:"3 × 8–15", unit:"repeticiones", rest:"90–120 s", steps:["Túmbate boca arriba, con rodillas flexionadas, pies apoyados y una mancuerna en cada mano.","Deja los codos a unos 30–45° del tronco. Empuja las mancuernas hacia arriba sin chocarlas.","Baja despacio hasta que los brazos contacten suavemente con el suelo; vuelve a empujar sin rebotar."], cue:"Mantén las muñecas alineadas con los antebrazos y los hombros apoyados.", easier:"Usa menos peso o trabaja un brazo cada vez si solo tienes una mancuerna."},
    row: {name:"Remo a una mano", muscle:"Espalda · bíceps", dose:"3 × 10–15", unit:"por lado", rest:"90–120 s", steps:["Adelanta una pierna y apoya la mano libre en tu propio muslo. Inclina el tronco desde la cadera, con espalda estable.","Con la mancuerna en la otra mano, lleva el codo hacia atrás y hacia la cadera.","Baja controladamente hasta extender el brazo. Completa ambos lados antes de descansar."], cue:"Evita girar el tronco o dar un tirón con el hombro.", easier:"Reduce el peso y la inclinación; conserva el apoyo en el muslo."},
    pushup: {name:"Flexiones", muscle:"Pecho · tríceps · abdomen", dose:"2 × 6–15", unit:"repeticiones", rest:"90–120 s", steps:["Apoya las manos algo más abiertas que los hombros y forma una línea estable con el cuerpo.","Flexiona los codos en diagonal hacia atrás y baja el pecho con control.","Empuja el suelo y vuelve a la posición inicial sin dejar caer la cadera."], cue:"Elige una variante que permita mover pecho y cadera al mismo tiempo.", easier:"Hazlas contra una pared o con las rodillas apoyadas."},
    lateralraise: {name:"Elevaciones laterales", muscle:"Hombro lateral", dose:"2 × 12–20", unit:"repeticiones", rest:"60–90 s", steps:["De pie, sujeta las mancuernas junto al cuerpo con los codos ligeramente flexionados.","Eleva los brazos por los lados, un poco por delante del tronco, hasta una altura cómoda cercana al hombro.","Desciende con control, sin dejar caer las mancuernas."], cue:"Evita encoger los hombros y balancear el cuerpo.", easier:"Reduce el peso, el recorrido o trabaja un brazo cada vez."},
    triceps: {name:"Extensión de tríceps en el suelo", muscle:"Tríceps", dose:"2 × 10–15", unit:"por brazo", rest:"60–90 s", steps:["Túmbate boca arriba con rodillas flexionadas. Sujeta una mancuerna en una mano y apunta el brazo hacia arriba.","Mantén el brazo bastante quieto y flexiona el codo, llevando la mancuerna al lado de la cabeza.","Extiende el codo con control y repite. Después cambia de brazo."], cue:"Usa un peso que controles durante todo el recorrido; no lo lleves sobre la cara.", easier:"Reduce el peso y ayuda a estabilizar el brazo con la mano libre."},
    curl: {name:"Curl de bíceps", muscle:"Bíceps", dose:"2 × 10–15", unit:"por brazo", rest:"60–90 s", steps:["De pie, mantén las mancuernas a los lados, con las palmas hacia delante.","Flexiona los codos sin adelantarlos mucho ni balancear el tronco.","Baja despacio hasta extender cómodamente los brazos. Puedes alternar los lados."], cue:"Mantén las muñecas rectas y las costillas sobre la pelvis.", easier:"Usa menos peso o haz un brazo cada vez."},
    goblet: {name:"Sentadilla goblet", muscle:"Cuádriceps · glúteos", dose:"3 × 8–15", unit:"repeticiones", rest:"90–120 s", steps:["Sujeta una mancuerna cerca del pecho. Coloca los pies en una separación cómoda, con las puntas ligeramente abiertas.","Flexiona rodillas y caderas, bajando entre las piernas hasta donde mantengas el control.","Empuja el suelo y vuelve a ponerte de pie manteniendo el apoyo de todo el pie."], cue:"Deja que las rodillas acompañen la dirección de los pies; no fuerces una profundidad.", easier:"Practica sin mancuerna o reduce la profundidad."},
    rdl: {name:"Peso muerto rumano", muscle:"Isquiotibiales · glúteos", dose:"3 × 8–15", unit:"repeticiones", rest:"90–120 s", steps:["De pie, sujeta las mancuernas delante de los muslos y flexiona ligeramente las rodillas.","Lleva la cadera hacia atrás, acercando las mancuernas a las piernas y manteniendo estable la espalda.","Cuando notes tensión en la parte posterior del muslo, empuja el suelo y lleva la cadera hacia delante."], cue:"No necesitas tocar el suelo ni inclinarte más si la espalda empieza a cambiar de posición.", easier:"Ensaya la bisagra sin peso o con un recorrido más corto."},
    bridge: {name:"Puente de glúteos", muscle:"Glúteos · parte posterior de las piernas", dose:"2 × 12–20", unit:"repeticiones", rest:"60–90 s", steps:["Túmbate boca arriba con rodillas flexionadas y pies apoyados, separados aproximadamente al ancho de las caderas.","Empuja con los pies y eleva la pelvis hasta alinear de forma cómoda muslos y tronco.","Aprieta suavemente los glúteos y vuelve al suelo con control."], cue:"Termina el movimiento con la cadera, sin arquear la zona lumbar.", easier:"Acorta el recorrido. Para progresar, sujeta una mancuerna sobre la pelvis con protección acolchada."},
    calf: {name:"Elevaciones de talones", muscle:"Pantorrillas", dose:"2 × 12–25", unit:"repeticiones", rest:"60–90 s", steps:["De pie sobre suelo firme, coloca los pies paralelos. Puedes tocar una pared para equilibrarte.","Eleva los talones, repartiendo el apoyo por la parte delantera de los pies.","Haz una pausa breve y baja los talones lentamente hasta el suelo."], cue:"Evita los rebotes y que los tobillos se venzan hacia los lados.", easier:"Empieza sin peso y con ambos pies; añade una mancuerna cuando resulte fácil."},
    abduction: {name:"Abducción de cadera de lado", muscle:"Glúteo medio · lateral de cadera", dose:"2 × 12–20", unit:"por lado", rest:"60–90 s", steps:["Túmbate de lado con la cabeza apoyada y la pelvis apilada. Flexiona ligeramente la pierna de abajo.","Mantén estirada la pierna superior y elévala un poco sin girar el cuerpo hacia atrás.","Baja con control y cambia de lado al terminar."], cue:"Se mueve la pierna de arriba; conserva el pie mirando aproximadamente hacia delante.", easier:"Reduce la altura y el número de repeticiones."},
    deadbug: {name:"Dead bug", muscle:"Abdomen · control del tronco", dose:"2 × 6–10", unit:"por lado", rest:"45–60 s", steps:["Boca arriba, levanta los brazos y coloca caderas y rodillas aproximadamente a 90°.","Al exhalar, aleja lentamente un brazo y la pierna contraria sin perder la posición del tronco.","Vuelve al centro y alterna los lados."], cue:"Detén el recorrido antes de que la espalda se arquee o contengas la respiración.", easier:"Mantén los brazos quietos y toca el suelo con un talón cada vez."},
    sideplank: {name:"Plancha lateral", muscle:"Abdomen lateral · estabilidad", dose:"2 × 15–30 s", unit:"por lado", rest:"45–60 s", steps:["Apóyate de lado sobre el antebrazo, con el codo debajo del hombro.","Eleva la cadera y conserva una línea estable entre hombros, pelvis y piernas.","Respira durante la posición y baja antes de perder la alineación."], cue:"Evita hundir el hombro o girar el pecho hacia el suelo.", easier:"Apoya las rodillas flexionadas y acorta el tiempo."},
    birddog: {name:"Bird dog", muscle:"Tronco · glúteos · estabilidad", dose:"2 × 6–8", unit:"por lado · pausa de 2–3 s", rest:"45–60 s", steps:["Colócate a cuatro apoyos, con manos bajo hombros y rodillas bajo caderas.","Alarga un brazo y la pierna contraria manteniendo pelvis y espalda estables.","Sostén 2–3 segundos, vuelve al centro y cambia de lado."], cue:"Alarga las extremidades sin elevarlas más de lo que puedas controlar.", easier:"Mueve solo un brazo o una pierna cada vez."},
    shoulder: {name:"Press de hombros de pie", muscle:"Hombros · tríceps", dose:"2 × 8–12", unit:"repeticiones", rest:"90–120 s", steps:["De pie, lleva las mancuernas junto a los hombros y coloca los antebrazos aproximadamente verticales.","Empuja hacia arriba en un recorrido cómodo, manteniendo abdomen y glúteos activos.","Baja de forma controlada hasta el punto de partida."], cue:"No compenses el peso arqueando la espalda; evita forzar un recorrido doloroso.", easier:"Usa menos peso o un brazo cada vez, con la otra mano apoyada en la cintura."},
    reversefly: {name:"Aperturas inversas inclinadas", muscle:"Deltoides posterior · espalda alta", dose:"2 × 12–20", unit:"repeticiones", rest:"60–90 s", steps:["Flexiona un poco las rodillas e inclina el tronco desde las caderas, con las mancuernas colgando.","Abre los brazos a los lados manteniendo los codos ligeramente flexionados.","Baja despacio y conserva la misma posición del tronco."], cue:"Usa poco peso; evita levantar los hombros hacia las orejas.", easier:"Reduce el recorrido o practica el movimiento sin mancuernas."},
    hammer: {name:"Curl martillo", muscle:"Bíceps · braquial · antebrazos", dose:"2 × 10–15", unit:"por brazo", rest:"60–90 s", steps:["De pie, sujeta las mancuernas con las palmas mirando hacia el cuerpo.","Flexiona los codos conservando ese agarre y sin balancearte.","Desciende con control. Puedes hacer ambos brazos o alternarlos."], cue:"Mantén los codos cerca del tronco y las muñecas alineadas.", easier:"Usa menos peso o trabaja un brazo cada vez."},
    split: {name:"Sentadilla dividida estática", muscle:"Cuádriceps · glúteos", dose:"3 × 8–12", unit:"por pierna", rest:"90–120 s", steps:["Coloca un pie delante y otro detrás, con separación lateral suficiente para equilibrarte. El pie trasero permanece en el suelo.","Flexiona las dos rodillas y baja la pelvis de forma controlada, manteniendo apoyado el pie delantero.","Empuja el suelo para subir. Mantén los pies quietos durante toda la serie y luego cambia de lado."], cue:"No hace falta apoyar el pie trasero en un banco; usa una pared como apoyo si lo necesitas.", easier:"Empieza sin mancuernas y con una bajada más corta."},
    walkout: {name:"Caminata de talones desde puente", muscle:"Isquiotibiales · glúteos", dose:"2 × 4–8", unit:"ciclos completos de ida y vuelta", rest:"60–90 s", steps:["Desde la posición de puente, eleva la pelvis y apoya los talones.","Da 2–4 pasos cortos con los talones alejándolos del cuerpo, hasta donde mantengas la pelvis estable.","Regresa con pasos cortos. Alejar y volver cuenta como una repetición."], cue:"No bloquees las rodillas ni sigas alejándote si la cadera cae o aparece un calambre.", easier:"Haz un puente bajo con los talones un poco más lejos y sostén 15–25 s, o vuelve al puente normal."},
    adduction: {name:"Aducción de cadera de lado", muscle:"Aductores · cara interna del muslo", dose:"2 × 12–20", unit:"por lado", rest:"60–90 s", steps:["Túmbate de lado. Cruza la pierna de arriba por delante y apoya su pie en el suelo.","Mantén estirada la pierna inferior y elévala unos centímetros.","Baja lentamente y repite antes de cambiar de lado."], cue:"Aquí se mueve la pierna de abajo, sin balancear la pelvis.", easier:"Reduce la altura o las repeticiones."},
    plank: {name:"Plancha frontal", muscle:"Abdomen · estabilidad", dose:"2 × 20–40 s", unit:"por serie", rest:"45–60 s", steps:["Apoya los antebrazos con los codos debajo de los hombros y extiende las piernas.","Eleva el cuerpo manteniendo alineados hombros, cadera y tobillos.","Respira con normalidad y termina la serie cuando ya no puedas mantener la posición."], cue:"Evita hundir la cintura o elevar demasiado la cadera.", easier:"Apoya las rodillas o haz series más cortas."},
    march: {name:"Marcha en el sitio", muscle:"Cardio sin saltos", dose:"1 minuto", unit:"primer y último minuto del circuito", rest:"Cambia al siguiente movimiento", steps:["Ponte de pie y alterna la elevación de los pies, como al caminar.","Acompaña con los brazos y conserva una postura cómoda.","Ajusta el ritmo para poder hablar, pero no cantar, durante el bloque moderado."], cue:"Pisa suavemente; no necesitas levantar mucho las rodillas.", easier:"Reduce el ritmo o la altura de los pasos."},
    sidesteps: {name:"Pasos laterales", muscle:"Cardio sin saltos", dose:"1 minuto", unit:"segundo minuto del circuito", rest:"Cambia al siguiente movimiento", steps:["Da un paso hacia un lado sobre el suelo y acerca el otro pie.","Repite hacia el lado contrario, con las rodillas ligeramente flexionadas.","Mueve los brazos de forma natural y mantén un ritmo continuo."], cue:"No se necesita un escalón ni una plataforma.", easier:"Da pasos más cortos y mueve menos los brazos."},
    boxing: {name:"Boxeo al aire", muscle:"Cardio sin pesas", dose:"1 minuto", unit:"tercer minuto del circuito", rest:"Cambia al siguiente movimiento", steps:["Coloca un pie algo adelantado, rodillas suaves y manos cerca de la cara.","Alterna golpes cortos hacia el frente sin bloquear los codos.","Recoge cada mano y acompaña con pequeños cambios de apoyo."], cue:"Hazlo con las manos vacías y sin golpes máximos.", easier:"Reduce el ritmo y mantén los pies en el sitio."},
    stepjacks: {name:"Step jacks sin salto", muscle:"Cardio de bajo impacto", dose:"1 minuto", unit:"cuarto minuto del circuito", rest:"Después vuelve a la marcha", steps:["De pie, da un paso lateral con un pie mientras elevas los brazos a una altura cómoda.","Vuelve al centro y baja los brazos.","Alterna el lado del paso, manteniendo siempre al menos un pie apoyado."], cue:"La variante de esta rutina no lleva saltos.", easier:"Eleva menos los brazos y reduce la amplitud del paso."}
  },
  days: [
    {id:1,title:"Torso A",subtitle:"Pecho, espalda, hombros y brazos",exercises:["floorpress","row","pushup","lateralraise","triceps","curl"]},
    {id:2,title:"Piernas A",subtitle:"Sentadilla, bisagra de cadera y trabajo lateral",exercises:["goblet","rdl","bridge","calf","abduction"]},
    {id:3,title:"Cardio + core",subtitle:"Movimiento continuo y control del tronco",cardio:["march","sidesteps","boxing","stepjacks"],exercises:["deadbug","sideplank","birddog"]},
    {id:4,title:"Torso B",subtitle:"Segunda sesión de torso, con énfasis en hombros",exercises:["row","floorpress","shoulder","reversefly","hammer","triceps"]},
    {id:5,title:"Piernas B",subtitle:"Trabajo unilateral, cadena posterior y abdomen",exercises:["split","rdl","walkout","calf","adduction","plank"]}
  ],
  upperMap:[
    ["Chest press","Press en el suelo","El suelo limita la profundidad del descenso."],
    ["Mariposa y aperturas en polea","Press en el suelo y flexiones","Entrenan el pecho; no reproducen el aislamiento de una apertura."],
    ["Pulley y remo sentado","Remo a una mano","La mano libre se apoya en el propio muslo."],
    ["Jalón alto, incluido agarre supino","Remo y curl","Cubren espalda y brazos, pero falta una tracción vertical equivalente."],
    ["Máquina y polea de tríceps","Extensión de tríceps en el suelo","Mantiene la extensión del codo con otra dirección de resistencia."],
    ["Curl en polea","Curl y curl martillo","La resistencia cambia según el ángulo del brazo."],
    ["Shoulder press","Press de hombros de pie","Requiere estabilizar el tronco."],
    ["Lateral raise y rear delts","Elevaciones laterales y aperturas inversas","Se utilizan mancuernas ligeras."],
    ["Elevaciones frontales","Press de hombros y de pecho","El deltoides anterior ya recibe trabajo; se reduce la duplicación."]
  ],
  lowerMap:[
    ["Prensa y extensión de piernas","Sentadilla goblet y dividida","Trabajan cuádriceps y glúteos; no aíslan la extensión de rodilla."],
    ["Curl femoral","Rumano y caminata de talones","Se combinan funciones; el rumano por sí solo no reproduce el curl."],
    ["Máquinas de abducción y aducción","Elevaciones de pierna de lado","Arriba para abducción, abajo para aducción."],
    ["Puente de glúteos","Puente en el suelo","Se conserva, con carga opcional sobre la pelvis."],
    ["Gemelos de pie y sentados","Elevaciones de talones de pie","Se simplifica el trabajo; cambia el estímulo respecto a hacerlo sentado."],
    ["Lower back machine y superman","Rumano y bird dog","Se priorizan bisagra de cadera y estabilidad; no son extensiones equivalentes."],
    ["Crunch y rotaciones de tronco","Dead bug, bird dog y planchas","El objetivo cambia hacia estabilidad; no reproduce la rotación dinámica."],
    ["Caminadora y escaladora","Marcha, pasos laterales, boxeo y step jacks","La intensidad se ajusta con el ritmo y la prueba del habla."]
  ],
  sources:[
    ["ACSM · Actualización de entrenamiento de fuerza, 2026","Regularidad, esfuerzo e individualización.","https://acsm.org/resistance-training-guidelines-update-2026/"],
    ["OMS · Recomendaciones de actividad física","150–300 minutos moderados y fortalecimiento al menos dos días por semana.","https://www.who.int/initiatives/behealthy/physical-activity"],
    ["Haugen et al., 2023 · Máquinas y peso libre","Revisión sistemática y metaanálisis.","https://link.springer.com/article/10.1186/s13102-023-00713-4"],
    ["Kikuchi y Nakazato, 2017 · Flexiones y press ligero","Ensayo pequeño de ocho semanas con cargas comparables.","https://pubmed.ncbi.nlm.nih.gov/29541130/"],
    ["Schoenfeld et al., 2015 · Cargas ligeras y altas","Ensayo en hombres con experiencia de entrenamiento.","https://pubmed.ncbi.nlm.nih.gov/25853914/"],
    ["Grgic et al., 2022 · Entrenar al fallo o detenerse antes","Metaanálisis de fuerza e hipertrofia.","https://pubmed.ncbi.nlm.nih.gov/33497853/"],
    ["CDC · Cómo medir la intensidad","Prueba del habla e intensidad relativa.","https://www.cdc.gov/physical-activity-basics/measuring/index.html"],
    ["Kinoshita et al., 2023 · Pantorrillas","Comparación de elevaciones de talones de pie y sentado.","https://pubmed.ncbi.nlm.nih.gov/38156065/"],
    ["ACE · Técnica del bird dog","Guía de ejecución y control del tronco.","https://www.acefitness.org/resources/everyone/exercise-library/14/bird-dog/"],
    ["Runna · Caminata de talones desde puente","Demostración de un ciclo de alejamiento y regreso.","https://support.runna.com/en/articles/8001396-glute-bridge-hamstring-walkout-exercise-tutorial"]
  ]
};
